title: ChangeScreenOrientation                 <script async type="text/javascript">var REPO="ChangeScreenOrientation";var DESC="Powershell shortcut to changing screen orientation";</script><script async type="text/javascript" src="/topmenu.js"></script>
description: Powershell shortcut to changing screen orientation
